version: '2.4'

services:
  x86_64:
    image: quay.io/pypa/manylinux_2_28_x86_64
    user: root
    stdin_open: true
    tty: true
    network_mode: host
    cap_add:
      - ALL
    volumes:
      - ./:/code
    working_dir: /code
    entrypoint: ["/bin/bash", "-c"]
    command: 
    - |
       # boto3 for interaction with AWS
       # twine to upload to TestPyPi
       # tox for automated tests
       python3.8 -m pip install --upgrade pip
       python3.8 -m pip install boto3 twine tox
       /bin/bash

  aarch64:
    image: quay.io/pypa/manylinux_2_28_aarch64
    user: root
    stdin_open: true
    tty: true
    network_mode: host
    cap_add:
      - ALL
    volumes:
      - ./:/code
    working_dir: /code
    entrypoint: ["/bin/bash", "-c"]
    command: 
    - |
       # boto3 for interaction with AWS
       # twine to upload to TestPyPi
       # tox for automated tests
       python3.8 -m pip install --upgrade pip
       python3.8 -m pip install boto3 twine tox
       /bin/bash
